

services:
  #-- services 1 the database 
  postgres_db: 
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=supersecret 
    volumes:
      - db_data:/var/lib/postgresql/data

  #-- services 2 the api 
  api_backend:
    image: nginx:alpine 
    ports:
      - "8000:80"
    depends_on:
      - postgres_db
    restart: unless-stopped 

volumes:
  db_data: 