apiVersion: v1 
kind: Secret 
metadata:
  name: hr-app-secrets 
type: Opaque 
stringData:
  MONGODB_URL: "mongodb+srv://jeffrinjojo1_db_user:W1knVgIBmTSCrIwB@cluster0.patv2cn.mongodb.net/?appName=Cluster0"

  
